sudo: required
services:
  - docker

script:
  - docker-compose build
  - docker images pthakur222/docker-spike_app

before_deploy:
  - docker login -u pthakur222 -p P.th@kur222

deploy:
  provider: script
  script: docker push pthakur222/docker-spike_app
  edge: true
  on:
    branch: master